### ISSUE TITLE
failed to read video id from data, it can only download the first episode

### ISSUE THREAD

**Issue by MisteryMonster** [chaert-s/skillshare-offline-use#1]
Here is the link that i try to offline use:

https://www.skillshare.com/classes/How-to-Animate-Action-Camera-Moves-Frame-by-Frame/626976235?via=user-profile

```
Traceback (most recent call last):
  File "downloader.py", line 27, in <module>
    dl.download_course_by_url(url, boolSubtitle, all_subs, boolResources)
  File "D:\Downloads\resource\skillshare\apps\skillshare-offline-use-main\skillshare.py", line 43, in download_course_by_url
    self.download_course_by_class_id(class_id, boolSubtitle, all_subs, boolResources)
  File "D:\Downloads\resource\skillshare\apps\skillshare-offline-use-main\skillshare.py", line 111, in download_course_by_class_id
    assert video_id, 'Failed to read video ID from data'
AssertionError: Failed to read video ID from data
```

**Comment by MisteryMonster** [comment]
Sorry for pasting the wrong value, after the correct one it works!
